// <auto-generated />

#nullable disable

using FormBuilder.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace FormBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(FormContext))]
    partial class FormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormBuilder.Core.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FormTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("Fields");

                    b.HasDiscriminator<int>("FieldType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FormBuilder.Core.Models.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("FormBuilder.Core.Models.CalculatedField", b =>
                {
                    b.HasBaseType("FormBuilder.Core.Models.Field");

                    b.Property<List<string>>("DependentFieldNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FormBuilder.Core.Models.UserField", b =>
                {
                    b.HasBaseType("FormBuilder.Core.Models.Field");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("FormBuilder.Core.Models.Field", b =>
                {
                    b.HasOne("FormBuilder.Core.Models.FormTemplate", null)
                        .WithMany("Fields")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FormBuilder.Core.Models.FormTemplate", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
